version: '3.7'

services:
  postgres:
    image: postgres:15.2
    container_name: user-company-sql-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB: "microservices"
    ports:
      - "5432:5432"